const router = require('express').Router();
const { protect } = require('../middlewares/auth.middleware');
const { loginLimiter } = require('../middlewares/rateLimiter');
const a = require('../controllers/auth.controller');
router.post('/register', loginLimiter, a.register);
router.post('/login', loginLimiter, a.login);
router.post('/two-factor/verify', loginLimiter, a.verifyFactor);
router.post('/forgot-password', loginLimiter, a.forgotPassword);
router.post('/reset-password/:token', loginLimiter, a.resetPassword);
router.get('/two-factor', protect, a.factorStatus);
router.post('/two-factor/setup', protect, loginLimiter, a.beginSetup);
router.post('/two-factor/confirm', protect, loginLimiter, a.confirmSetup);
router.delete('/two-factor/setup', protect, a.cancelSetup);
router.post('/two-factor/disable', protect, loginLimiter, a.disableFactor);
router.post('/logout', protect, a.logout);
router.post('/change-password', protect, loginLimiter, a.changePassword);
router.put('/change-password', protect, loginLimiter, a.changePassword);
module.exports = router;
