import { Component, Input, Output, EventEmitter, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { UiModule } from '../ui/ui.module';
export interface FilterOption { value: any; label: string; }
@Component({selector:'app-filter-select',standalone:true,imports:[CommonModule,UiModule],changeDetection:ChangeDetectionStrategy.OnPush,
 template:`<button type="button" hlmBtn variant="outline" class="filter-trigger" [brnMenuTriggerFor]="panel" [attr.aria-label]="label" [disabled]="disabled"><span>{{selectedLabel}}</span><i class="bx bx-chevron-down" aria-hidden="true"></i></button>
 <ng-template #panel><hlm-menu class="filter-menu" [attr.aria-label]="label"><hlm-menu-label>{{label}}</hlm-menu-label><button type="button" *ngFor="let option of options;trackBy:key" hlmMenuItemRadio class="filter-option" [checked]="value===option.value" (triggered)="valueChange.emit(option.value)" [attr.aria-label]="option.label"><span>{{option.label}}</span><i *ngIf="value===option.value" class="bx bx-check" aria-hidden="true"></i></button></hlm-menu></ng-template>`,
 styles:[`:host{display:block;min-width:0}.filter-trigger{width:100%;height:38px!important;justify-content:space-between;gap:10px;padding:0 12px!important;background:hsl(var(--card))!important;color:hsl(var(--foreground))!important;border:1px solid hsl(var(--border))!important;font-size:12px!important;border-radius:7px!important}.filter-trigger>span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.filter-trigger i{flex-shrink:0;font-size:16px;color:hsl(var(--muted-foreground))}.filter-trigger[aria-expanded=true]{border-color:hsl(var(--ring))!important}.filter-trigger:focus-visible{outline:2px solid hsl(var(--ring));outline-offset:2px}.filter-menu{display:block;min-width:190px;max-width:min(340px,calc(100vw - 24px));max-height:min(340px,calc(100dvh - 110px));overflow:auto;padding:5px!important;margin-top:5px;background:hsl(var(--popover))!important;color:hsl(var(--popover-foreground))!important;border:1px solid hsl(var(--border))!important;border-radius:10px!important;box-shadow:0 10px 30px #0002}.filter-menu hlm-menu-label{display:block;font-size:11px;color:hsl(var(--muted-foreground));padding:7px 9px}.filter-option{display:flex;align-items:center;gap:18px;justify-content:space-between;width:100%;padding:9px!important;min-height:36px;border:0!important;box-shadow:none!important;border-radius:6px!important;background:transparent;color:inherit;font-size:12px;cursor:pointer;text-align:start}.filter-option span{overflow-wrap:anywhere}.filter-option:hover,.filter-option:focus,.filter-option[aria-checked=true]{background:hsl(var(--accent))!important;color:hsl(var(--accent-foreground))!important}.filter-option:focus-visible{outline:2px solid hsl(var(--ring));outline-offset:-2px}`]})
export class FilterSelectComponent {
 @Input() label='Choose a filter';@Input() value:any;@Input() options:FilterOption[]=[];@Input() disabled=false;
 @Output() valueChange=new EventEmitter<any>();
 get selectedLabel(){return this.options.find(o=>o.value===this.value)?.label||this.label;}
 key=(_:number,o:FilterOption)=>o.value;
}
