import {Component,Directive,Input,OnChanges,inject} from '@angular/core';
import {CommonModule} from '@angular/common';
import {UiModule} from '../ui/ui.module';
import {ToastService} from '../../services/toast.service';
@Component({selector:'app-toast-outlet',standalone:true,imports:[CommonModule,UiModule],template:`<section class="toast-stack" aria-label="Notifications"><article *ngFor="let toast of service.messages()" class="toast-message" [class.toast-error]="toast.kind==='error'" [attr.role]="toast.kind==='error'?'alert':'status'" aria-atomic="true" (mouseenter)="service.pause(toast.id)" (mouseleave)="service.resume(toast.id)" (focusin)="service.pause(toast.id)" (focusout)="service.resume(toast.id)"><i class="bx" [class.bx-check-circle]="toast.kind==='success'" [class.bx-error-circle]="toast.kind==='error'" [class.bx-info-circle]="toast.kind==='info'" aria-hidden="true"></i><div><strong>{{toast.title}}</strong><p>{{toast.message}}</p></div><button hlmBtn type="button" variant="ghost" size="icon" aria-label="Dismiss notification" (click)="service.dismiss(toast.id)"><i class="bx bx-x" aria-hidden="true"></i></button></article></section>`,styles:[`:host{position:fixed;right:22px;top:22px;z-index:2000;pointer-events:none}.toast-stack{display:grid;gap:10px;width:min(390px,calc(100vw - 32px))}.toast-message{pointer-events:auto;display:flex;gap:12px;align-items:flex-start;padding:17px;border:1px solid hsl(var(--border));background:hsl(var(--card));color:hsl(var(--foreground));box-shadow:0 8px 25px #0002;border-radius:12px;font-family:Inter,Arial,sans-serif;animation:toast-arrive .18s ease-out}.toast-message>i{font-size:22px;color:hsl(var(--primary))}.toast-error>i{color:hsl(var(--destructive))}.toast-message>div{flex:1;min-width:0}.toast-message strong{font-size:12px;font-weight:600}.toast-message p{font-size:12px;line-height:1.6;margin:5px 0 0;overflow-wrap:anywhere;color:hsl(var(--muted-foreground))}.toast-message button{height:26px;width:26px;padding:0!important;flex-shrink:0}.toast-message button i{font-size:20px}@keyframes toast-arrive{from{opacity:0;transform:translateY(-8px)}to{opacity:1;transform:none}}@media(max-width:600px){:host{top:14px;right:16px}}@media(prefers-reduced-motion:reduce){.toast-message{animation:none}}`]})
export class ToastOutletComponent{readonly service=inject(ToastService);}
// Migration adapter for existing success state bindings; validation errors stay inline.
@Directive({selector:'[appToast]',standalone:true,host:{'[style.display]':"'none'"}})
export class ToastFeedbackDirective implements OnChanges{@Input()appToast='';private service=inject(ToastService);ngOnChanges(){if(typeof this.appToast==='string')this.service.show(this.appToast);}}
