import {Component,forwardRef,ViewChild,ElementRef} from '@angular/core';
import {CommonModule} from '@angular/common';
import {ControlValueAccessor,NG_VALUE_ACCESSOR} from '@angular/forms';
import {UiModule} from '../ui/ui.module';
@Component({selector:'app-tag-input',standalone:true,imports:[CommonModule,UiModule],providers:[{provide:NG_VALUE_ACCESSOR,useExisting:forwardRef(()=>TagInputComponent),multi:true}],template:`<div class="tag-field" [class.disabled]="disabled"><span class="tag-pill" *ngFor="let tag of tags;let i=index">{{tag}}<button type="button" [disabled]="disabled" [attr.aria-label]="'Remove topic '+tag" (click)="remove(i)"><i class="bx bx-x" aria-hidden="true"></i></button></span><input #entry id="editor-tags" aria-label="Add a topic" aria-describedby="tags-hint" [value]="draft" [disabled]="disabled" maxlength="60" (input)="draft=$any($event.target).value" (keydown)="key($event)" (blur)="commit();onTouched()" (paste)="paste($event)" placeholder="Add a topic…"></div><small id="tags-hint">Press Enter or comma to add a pill. Up to 20 topics, 50 characters each.</small><p *ngIf="error" role="alert" class="field-error">{{error}}</p>`,styles:[`.tag-field{display:flex;align-items:center;flex-wrap:wrap;gap:7px;min-height:46px;padding:9px;border:1px solid hsl(var(--input));border-radius:8px;background:hsl(var(--card));color:hsl(var(--foreground))}.tag-field:focus-within{outline:2px solid hsl(var(--ring));outline-offset:2px}.tag-pill{display:inline-flex;align-items:center;gap:6px;padding:5px 7px 5px 10px;background:hsl(var(--secondary));color:hsl(var(--secondary-foreground));border-radius:6px;font-size:11px;max-width:100%;overflow-wrap:anywhere}.tag-pill button{display:grid;place-items:center;border:0;background:transparent;color:inherit;padding:0;width:20px;height:20px}.tag-pill i{font-size:17px}.tag-field input{min-width:90px;flex:1;border:0;background:transparent;color:inherit;padding:5px;outline:none;font-size:12px}.disabled{opacity:.6}small{display:block;font-size:11px;color:hsl(var(--muted-foreground));line-height:1.7;margin-top:8px}`]})
export class TagInputComponent implements ControlValueAccessor{
 @ViewChild('entry')entry?:ElementRef<HTMLInputElement>;tags:string[]=[];draft='';disabled=false;error='';onChange:(v:string[])=>void=()=>{};onTouched=()=>{};
 writeValue(value:unknown){this.tags=Array.isArray(value)?value.filter(x=>typeof x==='string'):typeof value==='string'?value.split(',').map(x=>x.trim()).filter(Boolean):[];}
 registerOnChange(fn:any){this.onChange=fn;}registerOnTouched(fn:any){this.onTouched=fn;}setDisabledState(value:boolean){this.disabled=value;}
 commit(){if(this.disabled)return;this.error='';for(const raw of this.draft.split(',')){const tag=raw.trim();if(!tag)continue;if(tag.length>50){this.error='Each topic must be 50 characters or fewer.';continue;}if(this.tags.some(t=>t.toLowerCase()===tag.toLowerCase()))continue;if(this.tags.length>=20){this.error='Use no more than 20 topics.';break;}this.tags=[...this.tags,tag];}this.draft='';this.onChange(this.tags);}
 remove(i:number){this.tags=this.tags.filter((_,n)=>n!==i);this.onChange(this.tags);this.onTouched();this.entry?.nativeElement.focus();}
 key(event:KeyboardEvent){if(event.key==='Enter'||event.key===','){event.preventDefault();this.commit();}else if(event.key==='Backspace'&&!this.draft&&this.tags.length){event.preventDefault();this.remove(this.tags.length-1);}}
 paste(event:ClipboardEvent){const value=event.clipboardData?.getData('text');if(value?.includes(',')){event.preventDefault();this.draft+=value;this.commit();}}
}
